### ISSUE TITLE
Regular Expression and Slash - not really an issue

### ISSUE THREAD

**Issue by clupasq** [brianleroux/wtfjs#132]
What is described in the [2014-01-29-regular-expression-and-slash](https://github.com/brianleroux/wtfjs/blob/03afeec8b842c9811495e2e742e480ea4a17d5ea/posts/2014-01-29-regular-expression-and-slash.md) post is expected Regex behavior, not a JS WTF.

It's the same, for example, in [C#](http://ideone.com/jo8Eo9), [Python](http://ideone.com/O4k9W6) or [Ruby](http://ideone.com/SAhJQP).

**Comment by mcauser** [comment]
Read an ASCII lookup table. It'll all make sense.
`/[!-~]/.test("a");  // true`
`/[!-~]/.test("A");  // true`
`/[!-~]/.test("@");  // true`

**Comment by wolfascu** [comment]
@mcauser Yes, that's exactly my point. This is not a JavaScript WTF. It's perfectly normal behavior.

**Comment by qermit** [comment]
Some "smart" people use Character classes (https://en.wikipedia.org/wiki/Regular_expression#Character_classes)
Just guess why **[:alpha:]** is defined as **[A-Za-z]**

**Comment by shaedrich** [comment]
The document doesn't seem to exist anymore on master. So I guess, this issue can be closed, can't it?
