### ISSUE TITLE
new Number()

### ISSUE THREAD

**Issue by timdream** [brianleroux/wtfjs#135]
``` javascript
var x = 12;
var y = 12;
x === y // true

var x = new Number(12);
var y = new Number(12);
x === y // false
x == y // false

var x = y = new Number(12);
x === y // true
```

While it _might_ be useful to set two variables as references to the same `Number` instance object, the object instance does not have any method available to mutate it's internal primitive value, so this feature ended up only useful in confusing people.

Probably something inherited from Java?

**Comment by frontenddeveloping** [comment]
This is right behavior. Nothing special or wtf here.
```
new Number(12).valueOf() === new Number(12).valueOf();// true
```
