### ISSUE TITLE
Maintain this repository

### ISSUE THREAD

**Issue by nhducit** [brianleroux/wtfjs#143]
Hello everybody,

This repository seems to be inactive for a quite long time. It has 13 open issues and 35 Pull Requests. That's why I create a new github organization to fork and maintain this repository. 
Here is it: https://github.com/wthjs/wtfjs

If you want to maintain this repository, please let know by leaving comment on this issue.

Thanks.

**Comment by DTrejo** [comment]
Hey, we would almost definitely be happy to give you contrib. @brianleroux??

**Comment by brianleroux** [comment]
maybe some pull requests to see what fork/maintain means but yeah :+1:

**Comment by DTrejo** [comment]
@nhducit I will review / click merge on your PRs :)

**Comment by DTrejo** [comment]
We kinda need to fix the deploy situation. nodejitsu is gone. modulus i guess is the answer, or maybe google cloud allows free node apps, i don't know.

**Comment by brianleroux** [comment]
Maybe time to consider static site generator. Then either surge or s3?

**Comment by DTrejo** [comment]
yes. surge/github pages.
1) that means we need to move to harp or similar 2) preserve the URLs 3)
setup and republish to surge/gh-pages.

Then Bryan would point DNS at the new version.

@nhducit do you have any interest in doing the 1-3 above? If not that's
okay, you're not getting paid after all :)

Best,
D

**Comment by nhducit** [comment]
@DTrejo I will play with some static site generators next week. Do you have any recommend generator like harp?

**Comment by DTrejo** [comment]
Hey, yes, I recommend harp, because I have used it a lot, and it is made by
the creators of surge as well. It supports html/markdown/etc without any
configuration.

Once solution to broken links could be to write a command line tool that
creates symlinks to preserve the old URLs.

**Comment by brianleroux** [comment]
its baaaack 🔜 https://wtfjs.com/
