### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by bichotll** [brianleroux/wtfjs#145]
Hi guys,
looks like the website is down?

The last time I tried it just showed "nginx correctly installed"?

It might be a good idea to set it up on github.io?

**Comment by DTrejo** [comment]
Ah, yes, we need to redeploy to zeit now.

Hopefully I'll get to this soon. Thank you for telling us Jaume!
D

**Comment by DTrejo** [comment]
https://wtf-ztworcuzhw.now.sh

@brianleroux, here's how to change DNS. Tell me when you've done this so I
can finish setup?
Easy setup <https://zeit.co/blog/now-alias#easy-setup> via
https://zeit.co/blog/now-alias#easy-setup

The now <https://zeit.co/now> client verifies that your DNS is properly
configured when setting up a custom domain.

All you have to do is make sure that the custom domain or subdomain you're
configuring points to alias.zeit.co by using CNAME.

To configure apex records (e.g.: domain.com without www), we recommend you
use DNS servers that support the ALIAS records.
<https://zeit.co/blog/now-alias#account-settings-and-billing>
Thanks @rauchg!

**Comment by rauchg** [comment]
:) <3

**Comment by jerone** [comment]
Ping

**Comment by LDVSOFT** [comment]
Pong

**Comment by catalinred** [comment]
Still down :)

**Comment by onbjerg** [comment]
Bing bing bong bong, still down

**Comment by VictorChen** [comment]
downnnnnnn

**Comment by code-hunger** [comment]
No hope?

**Comment by zalsader** [comment]
Ping?

**Comment by maciejorlinski** [comment]
Hello?

**Comment by brianleroux** [comment]
its happening!!! sorry for the long delay. I started a port and will be pushing it up sooooooon

**Comment by brianleroux** [comment]
https://wtfjs.com/

**Comment by mastef** [comment]
`returning july 25 @ nodesummit`

:trollface:

**Comment by brianleroux** [comment]
Not trollin' fwiw! Just good 'ol fashioned *conference driven development*. (Always best way to motivate this guy!)
