### ISSUE TITLE
true == 'true' is not true

### ISSUE THREAD

**Issue by joeytwiddle** [brianleroux/wtfjs#80]
The section "false isnt false" claims that:

```
true == 'true'     // true
false == 'false';  // false
```

But in fact the first line also resolves to `false`.  Please correct it!

You may prefer to write that section like this:

```
false == '0';      // true
false == 'false';  // false
```

**Comment by brianleroux** [comment]
removed in v5 coming 🔜

**Comment by jas7553** [comment]
Glad to see this is getting straightened out 🙌
